// Tokens derived from DESIGN.md frontmatter. This is the only source of colors,
// typography, radii, and spacing. No raw hex codes elsewhere in the codebase.

const lightPalette = {
  surface: '#fbf9f9',
  surfaceDim: '#dbdad9',
  surfaceBright: '#fbf9f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f5f3f3',
  surfaceContainer: '#efeded',
  surfaceContainerHigh: '#e9e8e7',
  surfaceContainerHighest: '#e3e2e2',
  onSurface: '#1b1c1c',
  onSurfaceVariant: '#3e4946',
  inverseSurface: '#303031',
  inverseOnSurface: '#f2f0f0',
  outline: '#6e7976',
  outlineVariant: '#bec9c5',
  surfaceTint: '#046b5e',
  primary: '#004f45',
  onPrimary: '#ffffff',
  primaryContainer: '#00695c',
  onPrimaryContainer: '#94e5d5',
  inversePrimary: '#84d5c5',
  secondary: '#5d5f5e',
  onSecondary: '#ffffff',
  secondaryContainer: '#dcdddc',
  onSecondaryContainer: '#5f6161',
  tertiary: '#703321',
  onTertiary: '#ffffff',
  tertiaryContainer: '#8d4a36',
  onTertiaryContainer: '#ffcabb',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#a0f2e1',
  primaryFixedDim: '#84d5c5',
  onPrimaryFixed: '#00201b',
  onPrimaryFixedVariant: '#005046',
  background: '#fbf9f9',
  onBackground: '#1b1c1c',
  backgroundAccent: '#f3fbf8',
  surfaceElevated: '#fffefd',
  surfaceOverlay: '#f8f6f5',
  heroGradientStart: '#0f7668',
  heroGradientMid: '#0b5f54',
  heroGradientEnd: '#164e63',
  heroGlowMint: '#8de4d2',
  heroGlowPeach: '#ffd6c2',
  tabSurface: '#fffaf7',
  tabBorder: '#d7e4df',
  tabActive: '#e2f7f0',
  warningContainer: '#fff3cd',
  onWarningContainer: '#5c4400',
  successContainer: '#d4edda',
  onSuccessContainer: '#0f5132',
} as const;

const darkPalette = {
  surface: '#121212',
  surfaceDim: '#1a1a1a',
  surfaceBright: '#2a2a2a',
  surfaceContainerLowest: '#0f0f0f',
  surfaceContainerLow: '#1a1a1a',
  surfaceContainer: '#232323',
  surfaceContainerHigh: '#2c2c2c',
  surfaceContainerHighest: '#353535',
  onSurface: '#e8e8e8',
  onSurfaceVariant: '#a8a8a8',
  inverseSurface: '#e8e8e8',
  inverseOnSurface: '#ffffff',
  outline: '#888888',
  outlineVariant: '#555555',
  surfaceTint: '#5dd6c4',
  primary: '#84d5c5',
  onPrimary: '#ffffff',
  primaryContainer: '#005046',
  onPrimaryContainer: '#94e5d5',
  inversePrimary: '#004f45',
  secondary: '#bcbdbc',
  onSecondary: '#2a2a2a',
  secondaryContainer: '#424242',
  onSecondaryContainer: '#d7d8d7',
  tertiary: '#ffb59f',
  onTertiary: '#4a2418',
  tertiaryContainer: '#652f25',
  onTertiaryContainer: '#ffcabb',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffb4ab',
  primaryFixed: '#a0f2e1',
  primaryFixedDim: '#84d5c5',
  onPrimaryFixed: '#00201b',
  onPrimaryFixedVariant: '#005046',
  background: '#0f0f0f',
  onBackground: '#e8e8e8',
  backgroundAccent: '#1a2f2b',
  surfaceElevated: '#252525',
  surfaceOverlay: '#1f1f1f',
  heroGradientStart: '#0b5f54',
  heroGradientMid: '#083d36',
  heroGradientEnd: '#0d3a43',
  heroGlowMint: '#5dd6c4',
  heroGlowPeach: '#ffb594',
  tabSurface: '#1a1a1a',
  tabBorder: '#333333',
  tabActive: '#0d3d39',
  warningContainer: '#664d00',
  onWarningContainer: '#ffe0b2',
  successContainer: '#1b5e20',
  onSuccessContainer: '#b3e5b3',
} as const;

export const palette = lightPalette;

export const spacing = {
  xs: 4,
  sm: 12,
  base: 8,
  md: 16,
  lg: 24,
  xl: 32,
  containerMargin: 20,
  gutter: 12,
} as const;

export const radius = {
  sm: 4,
  base: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
} as const;

export const typography = {
  displayLg: { fontFamily: 'Inter', fontSize: 36, fontWeight: '700' as const, lineHeight: 43, letterSpacing: -0.72 },
  headlineMd: { fontFamily: 'Inter', fontSize: 24, fontWeight: '600' as const, lineHeight: 31 },
  bodyBase: { fontFamily: 'Inter', fontSize: 16, fontWeight: '400' as const, lineHeight: 25 },
  bodySm: { fontFamily: 'Inter', fontSize: 14, fontWeight: '400' as const, lineHeight: 22 },
  labelCaps: { fontFamily: 'Inter', fontSize: 12, fontWeight: '600' as const, lineHeight: 14, letterSpacing: 0.6 },
  currencyDisplay: { fontFamily: 'Inter', fontSize: 32, fontWeight: '700' as const, lineHeight: 32 },
} as const;

export const elevation = {
  card: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 3,
  },
  fab: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
} as const;

export type Palette = typeof lightPalette;

export function getPalette(theme: 'light' | 'dark'): Palette {
  return theme === 'dark' ? (darkPalette as unknown as Palette) : lightPalette;
}

export const tokens = { palette, spacing, radius, typography, elevation } as const;
export type Tokens = typeof tokens;
